/*
=============================================================================
MODULE: backend/mmSecrets.js
VERSION: marianmadrid4001 (v21.0.0-LTS-canonical-secrets)
RESPONSIBILITY: Catalog of Wix Secrets Manager key names.
STANDARDS: G10 ASCII Strict (0 non-ASCII characters).
=============================================================================
*/

export const SECRETS = Object.freeze({
    FISCAL_KEY: "SECRET_FISCAL_KEY",
    FISCAL_NIF_EMISOR: "FISCAL_NIF_EMISOR",
    AUTH_JWT_KEY: "SECRET_AUTH_JWT_KEY",
    ADMIN_EMAILS: "ADMIN_EMAILS",
    CAJERO_EMAILS: "CAJERO_EMAILS",
    POWER_AUTOMATE: "POWER_AUTOMATE_TOKEN",
    SENDGRID_API_KEY: "SENDGRID_API_KEY",
    SENDGRID_FROM_EMAIL: "SENDGRID_FROM_EMAIL",
    RESEND_API_KEY: "RESEND_API_KEY",
    RESEND_FROM_EMAIL: "RESEND_FROM_EMAIL",
    MAPA_STAFF: "MAPA_STAFF",
    APP_KEY: "APP_KEY",
    BOOKINGS_API_TOKEN: "BOOKINGS_API_TOKEN",
    MARIAN_ASSISTANT_OPENAI_KEY: "MARIAN_ASSISTANT_OPENAI_KEY",
    M365_GRAPH_CLIENT_ID: "M365_CLIENT_ID",
    M365_GRAPH_CLIENT_SECRET: "M365_CLIENT_SECRET",
    M365_GRAPH_TENANT_ID: "M365_TENANT_ID",
    M365_GRAPH_SITE_ID: "M365_SITE_ID",
    M365_GRAPH_LIST_ID: "M365_LIST_ID",
});